[providers]
providers = ["node"]

[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"