name: Supabase Keepalive

on:
  schedule:
    - cron: '0 12 */3 * *'  # Every 3 days at 12:00 PM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Keepalive Function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/keepalive" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"